# Generated by Django 5.1.7 on 2025-09-23 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_postulacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='portal.vacante')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='portal.postulacion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.pregunta')),
            ],
        ),
    ]
