# Generated by Django 5.1.7 on 2025-09-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_pregunta_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='estudios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experiencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
