# Generated by Django 5.1.7 on 2025-09-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_profile_cv_profile_estudios_profile_experiencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_postulantes/'),
        ),
    ]
