# Generated by Django 5.1.7 on 2025-10-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_profile_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('visto', 'Visto'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='enviado', max_length=20),
        ),
    ]
