# Generated by Django 5.1.7 on 2025-10-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_postulacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='fecha_visto',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
