# Generated by Django 5.1.7 on 2025-10-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_postulacion_fecha_visto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='estudios',
            new_name='habilidades_blandas',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experiencia',
        ),
        migrations.AddField(
            model_name='profile',
            name='anios_experiencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='area_profesional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='disponibilidad',
            field=models.CharField(blank=True, choices=[('inmediata', 'Inmediata'), ('15_dias', 'Dentro de 15 días'), ('30_dias', 'Dentro de 30 días'), ('otros', 'Otros')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='habilidades_tecnicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='movilidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='nivel_educacion',
            field=models.CharField(blank=True, choices=[('basica', 'Educación básica'), ('media', 'Educación media'), ('tecnico', 'Técnico'), ('profesional', 'Profesional'), ('postgrado', 'Postgrado / Magíster / Doctorado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pretension_renta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tipo_jornada',
            field=models.CharField(blank=True, choices=[('completa', 'Jornada completa'), ('media', 'Media jornada'), ('por_proyecto', 'Por proyecto / freelance')], max_length=20, null=True),
        ),
    ]
