# Generated by Django 5.1.7 on 2025-10-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_rename_estudios_profile_habilidades_blandas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='fecha_visto',
        ),
    ]
