# Generated by Django 5.1.7 on 2025-10-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_profile_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='etapa_proceso',
            field=models.CharField(choices=[('sin_avance', 'Sin avance'), ('descartado', 'Descartado'), ('entrevista_rrhh', 'Entrevista con RRHH'), ('entrevista_area', 'Entrevista con jefe de area'), ('oferta', 'Oferta extendida'), ('contratado', 'Contratado')], default='sin_avance', max_length=30),
        ),
    ]
